apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment 
  namespace: mvician
spec:
  template:
    spec:
      containers:
        - image: quay.io/ericbos1/senti:v7
          env:
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: apikey
            - name: url
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: url
